apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: outlink-topic-model
spec:
  default:
    predictor:
      custom:
        name: outlink-topic-model
        container:
          image: accraze/outlinks-topic-model
